<?php
/* $Id: en.lang.php 5268 2011-09-01 16:33:02Z gaika $ */

define("NETCAT_MODULE_MINISHOP_DESCRIPTION", "Minishop");

define("NETCAT_MODULE_MINISHOP_INFOBLOCK_MODE", "Infoblock mode");
define("NETCAT_MODULE_MINISHOP_INFOBLOCK_GOOD_MODE", "Infoblocks 'Good' mode");

define("NETCAT_MODULE_MINISHOP_PUT_GOOD_IN_CART", "Add to cart");
define("NETCAT_MODULE_MINISHOP_MASSPUT_GOOD_IN_CART", "Add goods to your cart");
define("NETCAT_MODULE_MINISHOP_GOOD_ALREADY_IN_CART", "This goods are already in your cart");
define("NETCAT_MODULE_MINISHOP_GOOD_PUT_IN_CART_OK", "Goods were successfully added to your cart");
define("NETCAT_MODULE_MINISHOP_GOOD_PUT_IN_CART_ERROR", "An error occurred while adding goods to your cart.");

// Cart attributes
define("NETCAT_MODULE_MINISHOP_CART_YOURS", "Your");
define("NETCAT_MODULE_MINISHOP_CART_TITLE1", "cart");
define("NETCAT_MODULE_MINISHOP_CART_EMPTY", "is empty");
define("NETCAT_MODULE_MINISHOP_CART_ATYOURS", "In your");
define("NETCAT_MODULE_MINISHOP_CART_TITLE2", "cart");
define("NETCAT_MODULE_MINISHOP_CART_EMPTY_TEXT", "Your cart is empty");

define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT1", "cart");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT2", "carts");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT3", "cart");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_SUM", "sum");
define("NETCAT_MODULE_MINISHOP_CART_GOODS", "In your cart");

define("NETCAT_MODULE_MINISHOP_CART_DISP_NAME", "Article name");
define("NETCAT_MODULE_MINISHOP_CART_DISP_PRICE", "Price");
define("NETCAT_MODULE_MINISHOP_CART_DISP_VALUE", "Number");
define("NETCAT_MODULE_MINISHOP_CART_DISP_COST", "Value");
define("NETCAT_MODULE_MINISHOP_CART_DISP_TOTAL", "Total");

define("NETCAT_MODULE_MINISHOP_GO_TO_CART", "Go to your cart");
define("NETCAT_MODULE_MINISHOP_CART_RECALC", "Recalc your cart");
define("NETCAT_MODULE_MINISHOP_CART_ORDER", "Checkout order");
define("NETCAT_MODULE_MINISHOP_CHECKOUT", "Ordering");
define("NETCAT_MODULE_MINISHOP_AUTH", "Authorization");
define("NETCAT_MODULE_MINISHOP_TEXT_SUGGEST", "Authorization is not required, but after authentication you can view your order history.");
define("NETCAT_MODULE_MINISHOP_TEXT_AUTH", "To place an order you have to register or log in ..");

define("NETCAT_MODULE_MINISHOP_PIECES", "pc.");

define("NETCAT_MODULE_MINISHOP_CURRENCY_RUB", "$.");

//Admin
define("NETCAT_MODULE_MINISHOP_ADMIN_SAVE_OK", "Saved successfully");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB", "Information");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TABLENAME", "Information about orders");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TODAYROW", "Today");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_YESTERDAYROW", "Yesterday");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_MONTHROW", "This month");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_LASTMONTHROW", "Last month");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TOTALROW", "For all the time");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_NEWCOL", "Not processed");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_PROCESSCOL", "In processing");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_DONECOL", "Done");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_DENYCOL", "Refusal");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TOTALCOL", "Total");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB", "Preferences");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB", "Discounts");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB", "Displaying");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB", "Email templates");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SYSTEM_TAB", "System");

define("NETCAT_MODULE_MINISHOP_ADMIN_SETTINGS_SAVE", "Save");
define("NETCAT_MODULE_MINISHOP_ADMIN_SETTINGS_GENERATE_TEMPLATE", "generate");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_TITLE", "Shop preferences");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOPNAME", "Shop name");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOP_CURRENCY", " Shop currency");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_RUB", "$");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_ALT", " other ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_ALT_NAME", " short names (e.g. RUB, EUR)");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ORDERS_STAT", " Keep records of orders ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ORDERS_STAT_TITLE", "Statistics of orders");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_ONORDER", " Authorization for ordering ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_NO", " don't require ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_OFFER", " offer ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_YES", " require ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DELIVERY", "Show delivery options");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DELIVERY_SETTINGS", "settings");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_PAYMENT", "Show payment options");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_NOTIFY_TITLE", " Notification preferences ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_NOTIFYCLIENT", " send a email to the buyer of a new order");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOPEMAIL", "Shop email");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ADMINEMAIL", " Shop admin's email");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DEFAULT_EMAIL", "default");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ONORDERSUM", " Provide discounts depending on the amount of the order");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_CALC", " Discount calc");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ORDER_SUM", " Order sum");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_GREATERTHAN", "more ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_AND", " and ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_OR", " or ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_LESSTHAN", " less than");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNTSUM", "  discount ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_PERCENTAGE", " percentage ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ADD", " add");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DELETE", " delete ");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_ACTION", " Action when placed in the basket");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_RELOAD", " reload current page");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NORELOAD", " don't reload current page");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_ALERT", " notify by alert window ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_DIV", " notify by new page layer");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_NONE", " don't notify ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_AJAXNOTIFY", " Advance notice by the dialog box");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_BUTTON", " Element 'Add to cart' ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS0", " text link ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS1", " image ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS2", "text with image ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS3", " button ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS4", " Button with count area ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_ALTERNATE", " Alternative template ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_MASSPUT_ALTERNATE", " button mass placement of goods ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_INCART", " Label 'Article is in your cart' ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ASTEXT", " text label ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ASIMG", " image ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ALTERNATE", " Other template ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY", "Adding to the cart notify");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY_ALERT_TEXT", "Dialogue window text");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY_DIV_TEXT", "Alert window text");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART", " Cart ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_NONEMPTY", " Informer is not an empty cart ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_EMPTY", " Informer is an empty  cart ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_AFTERTEXT", " Print text after table on cart page");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM", " Ordering form ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_INLINE", "show form on cart page");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_USECAPTCHA", " protect ordering form(captcha) ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_AFTERTEXT", " Template of text after ordering");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_AUTHTEMPLATE", " Template of authentication form while ordering ");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL", "Email to admin after new order");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL_SUBJECT", " Title ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL_TEXT", " Text ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_CLIENTMAIL", " Email to customer ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_GOODSTEMPLATE", " Template for printing list of goods ");
?>