<?php
/* $Id: ru_utf8.lang.php 5268 2011-09-01 16:33:02Z gaika $ */

define("NETCAT_MODULE_MINISHOP_DESCRIPTION", "Минимагазин");

define("NETCAT_MODULE_MINISHOP_INFOBLOCK_MODE", "Режим работы инфоблоков магазина");
define("NETCAT_MODULE_MINISHOP_INFOBLOCK_GOOD_MODE", "Инфоблоки 'Товар' работают в режиме");

define("NETCAT_MODULE_MINISHOP_PUT_GOOD_IN_CART", "В корзину");
define("NETCAT_MODULE_MINISHOP_MASSPUT_GOOD_IN_CART", "Положить товары в корзину");
define("NETCAT_MODULE_MINISHOP_GOOD_ALREADY_IN_CART", "Этот товар уже в корзине");
define("NETCAT_MODULE_MINISHOP_GOOD_PUT_IN_CART_OK", "Товар успешно добавлен в корзину");
define("NETCAT_MODULE_MINISHOP_GOOD_PUT_IN_CART_ERROR", "При добавлении товара в корзину произошла ошибка");

// Cart attributes
define("NETCAT_MODULE_MINISHOP_CART_YOURS", "Ваша");
define("NETCAT_MODULE_MINISHOP_CART_TITLE1", "корзина");
define("NETCAT_MODULE_MINISHOP_CART_EMPTY", "пуста");
define("NETCAT_MODULE_MINISHOP_CART_ATYOURS", "В вашей");
define("NETCAT_MODULE_MINISHOP_CART_TITLE2", "корзине");
define("NETCAT_MODULE_MINISHOP_CART_EMPTY_TEXT", "Ваша корзина пуста");

define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT1", "товар");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT2", "товаров");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_COUNT3", "товара");
define("NETCAT_MODULE_MINISHOP_CART_GOODS_SUM", "на сумму");
define("NETCAT_MODULE_MINISHOP_CART_GOODS", "В вашей корзине");

define("NETCAT_MODULE_MINISHOP_CART_DISP_NAME", "Название товара");
define("NETCAT_MODULE_MINISHOP_CART_DISP_PRICE", "Цена");
define("NETCAT_MODULE_MINISHOP_CART_DISP_VALUE", "Количество");
define("NETCAT_MODULE_MINISHOP_CART_DISP_COST", "Стоимость");
define("NETCAT_MODULE_MINISHOP_CART_DISP_TOTAL", "Всего");

define("NETCAT_MODULE_MINISHOP_GO_TO_CART", "Перейти в корзину");
define("NETCAT_MODULE_MINISHOP_CART_RECALC", "Пересчитать корзину");
define("NETCAT_MODULE_MINISHOP_CART_ORDER", "Оформить заказ");
define("NETCAT_MODULE_MINISHOP_CHECKOUT", "Оформление заказа");
define("NETCAT_MODULE_MINISHOP_AUTH", "Авторизация");
define("NETCAT_MODULE_MINISHOP_TEXT_SUGGEST", "Авторизация не обязательна, но авторизовавшись Вы можете просматривать свою историю заказов.");
define("NETCAT_MODULE_MINISHOP_TEXT_AUTH", "Для оформления заказа Вам надо зарегистрироваться или авторизоваться..");

define("NETCAT_MODULE_MINISHOP_PIECES", "шт");

define("NETCAT_MODULE_MINISHOP_CURRENCY_RUB", "руб.");

//Admin
define("NETCAT_MODULE_MINISHOP_ADMIN_SAVE_OK", "Настройки успешно сохранены");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB", "Информация");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TABLENAME", "Информация о заказах");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TODAYROW", "Сегодня ");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_YESTERDAYROW", "Вчера");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_MONTHROW", "В этом месяце");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_LASTMONTHROW", "В прошлом месяце");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TOTALROW", "За все время");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_NEWCOL", "Не обработано");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_PROCESSCOL", "В обработке");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_DONECOL", "Исполнено");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_DENYCOL", "Отказ");
define("NETCAT_MODELE_MINISHOP_ADMIN_TEMPLATE_INFO_TAB_TOTALCOL", "Всего");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB", "Настройки");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_GENERAL_TAB", "Общие");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB", "Скидки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB", "Отображение");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB", "Шаблоны писем");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SYSTEM_TAB", "Системные");

define("NETCAT_MODULE_MINISHOP_ADMIN_SETTINGS_SAVE", "Сохранить");
define("NETCAT_MODULE_MINISHOP_ADMIN_SETTINGS_GENERATE_TEMPLATE", "сгенерировать");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_TITLE", "Настройки магазина");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOPNAME", "Название магазина");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOP_CURRENCY", " Валюта магазина ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_RUB", " рубли ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_ALT", "другая");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_CURRENCY_ALT_NAME", "сокращенное наименование, например USD или EUR");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ORDERS_STAT", " Вести учет заказов ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ORDERS_STAT_TITLE", " Статистика по заказам ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_ONORDER", " Авторизация при оформлении заказа");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_NO", " не требовать ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_OFFER", " предлагать ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_AUTHORIZE_YES", " требовать ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DELIVERY_PAYMENT", "Доставка и оплата");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DELIVERY", "Показывать варианты доставки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DELIVERY_SETTINGS", "настроить");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_PAYMENT", "Показывать варианты оплаты");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_NOTIFY_TITLE", " Настройки уведомлений ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_NOTIFYCLIENT", " отправлять покупателю письмо о новом заказе");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_SHOPEMAIL", " Email c которого отправляются письма");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_ADMINEMAIL", " Email администратора для уведомления о заказах");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_SETTINGS_TAB_DEFAULT_EMAIL", "по умолчанию");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ERROR_VALUE", "Не введено значение скидки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ERROR_LIMIT", "Не заданы ценовые границы скидки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ERROR_LOWER", "Верхняя граница скидки меньше нижней");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ERROR_RANGE", "Некоторые скидки применяются к одному и тому же ценовому диапозону");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_ONORDERSUM", " Предоставлять скидки в зависимости от суммы заказа");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNT_CALC", " Расчет скидки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ORDER_SUM", " Сумма заказа");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ORDER_FROM", "от");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ORDER_TO", "до");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_GREATERTHAN", " больше ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_AND", " и ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_OR", " или ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_LESSTHAN", " меньше");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DISCOUNTSUM", "скидка");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_PERCENTAGE", " в процентах");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_ADD", " добавить");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISCOUNT_TAB_DELETE", "удалить");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_ACTION", " Действие при помещении в корзину");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_RELOAD", " перезагрузить текущую страницу");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NORELOAD", " не перезагружать страницу");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_ALERT", " уведомить о помещении в корзину при помощи диалогового окна ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_DIV", " уведомить о помещении в корзину при помощи всплывающего слоя");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_NOTIFY_NONE", " не уведомлять ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CARTPUT_AJAXNOTIFY", " предварительно уведомить о помещении в корзину при помощи диалогового окна");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_BUTTON", " Элемент 'положить в корзину' ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS0", " текстовая ссылка ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS1", " картинка ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS2", "текст с картинкой ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS3", " кнопка ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_AS4", " кнопка с полем количества ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_PUT_ALTERNATE", " Альтернативный шаблон ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_MASSPUT_ALTERNATE", " Вывод кнопки массового помещения товаров ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NO_PRICE", " При отсутствии у товара цены вывести текст");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_INCART", " Надпись 'товар в корзине' ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ASTEXT", " текстовая надпись ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ASIMG", " картинка ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ALREADY_ALTERNATE", " Другой шаблон ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY", "Уведомление о помещении в корзину");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY_ALERT_TEXT", "Текст в диалоговом окне");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_NOTIFY_DIV_TEXT", "Текст во всплывающем слое");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART", " Корзина ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_NONEMPTY", " Информер не пустой корзины ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_EMPTY", " Информер пустой корзины ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_CART_AFTERTEXT", " Вывести на странице корзины после таблицы текст");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM", " Форма оформления заказа ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_INLINE", "показывать форму на странице с корзиной");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_USECAPTCHA", " защищать картинкой форму оформления заказа (captcha) ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_AFTERTEXT", " Шаблон текста после оформления заказа ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_DISPLAY_TAB_ORDERFORM_AUTHTEMPLATE", " Шаблон формы авторизации при оформлении заказа ");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL", "Письмо администратору о новом заказе");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL_SUBJECT", " Заголовок письма");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL_TEXT", " Тело письма");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_ADMINMAIL_HTML", " HTML-письмо");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_CLIENTMAIL", " Письмо покупателю ");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_GOODSTEMPLATE", " Шаблон для вывода списка товаров ");

define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM", "Системные настройки");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_CART_COMPONENT", "Компонент \"Корзина\"");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_ORDER_COMPONENT", "Компонент \"Заказы\"");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_ORDERADD_LINK", "Ссылка на оформление заказа");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_ORDER_LINK", "Ссылка на заказы");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_CART_LINK", "Ссылка на корзину");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_ORDER_CC", "Номер компонента в разделе с заказами");
define("NETCAT_MODULE_MINISHOP_ADMIN_TEMPLATE_MAILS_TAB_SYSTEM_CART_CC", "Номер компонента в разделе с корзиной");